[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  force = true

[[headers]]
  for = "/*"
  [headers.values]
    Strict-Transport-Security = "max-age=31536000; includeSubDomains"
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    Content-Security-Policy = "default-src 'self' https: 'unsafe-inline' 'unsafe-eval' https://www.google-analytics.com https://www.googletagmanager.com;"
    Referrer-Policy = "strict-origin-when-cross-origin" 