[[headers]]
  for = "/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000"
    
[[headers]]
  for = "/styles.v2.css"
  [headers.values]
    Cache-Control = "no-cache, no-store, must-revalidate"
    
[[headers]]
  for = "/*.webp"
  [headers.values]
    Cache-Control = "public, max-age=31536000"

[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000"
    Access-Control-Allow-Origin = "*"

# Only redirect non-asset requests to index.html
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  force = false
  conditions = {Not = [
    {Path = ["/assets/*", "/*.css", "/*.js", "/*.json", "/*.ico", "/*.png", "/*.jpg", "/*.jpeg", "/*.gif", "/*.svg", "/*.webp", "/*.mp4", "/*.woff", "/*.woff2", "/*.ttf", "/*.eot"]}
  ]} 